---
title: "Assignment 1: Introduction"
author: Samantha Jensen
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: My only real experience with data analytics is with Excel. I used R briefly last year in undergrad for my statistics class but it was very basic. I have no experience using Git. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident that I can keep up with the material as I have some coding background through C++. While it is a very different language, I have experience with different data structures. Additionally, I am excited about the flipped classroom because I feel like I will have an easier time keeping up with the lecture if I am confused. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am a little bit apprehensive about the different saving, pushing/committing techniques because I have not used Git or R but I feel as though those will come easier with time. I was able to get everything sorted out during lab today(9/5) so I am confident that my contianer and Git are linked correctly which I was apprehensive about prior to lab. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/samantha-jensen/EDE_Fall2024

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
